#!/usr/bin/env node
/*
 * Translate the retained PERFIN draw.io sources to English.
 *
 * core_gen.py keeps the geometric source for diagrams 03--07, 09--10 and
 * 12. Run this script after a regeneration so the shared VI/EN report uses
 * one English-labelled diagram set, as required by Guideline-report.md.
 */

const fs = require("fs");
const path = require("path");

const drawioDir = path.join(__dirname, "drawio");
const files = [
  "01-system-context", "02-runtime-architecture", "03-deployment",
  "04-domain-class", "05-physical-erd", "06-llm-boundary",
  "07-conversation-state", "09-multimodal-flow", "10-feedback-flow",
  "12-goal-flow",
];

// Longer, diagram-specific phrases come first; short shared labels come last.
const replacements = [
  ["Đã cancel&#xa;no data write", "Cancelled&#xa;no data write"],
  ["Result chưa lưu&#xa;or return to edit", "Unsaved result&#xa;or return to edit"],
  ["Lưu trữ bền vững, authoritative data", "Persistent authoritative storage"],
  ["User và hội thoại", "User and conversation"],
  ["Ledger xác định", "Deterministic ledger"],
  ["LLM chỉ chuyển đổi ngữ nghĩa và diễn giải facts; validation, side effect, phép tính và system of record luôn thuộc lõi xác định.", "The LLM only performs semantic conversion and fact narration; validation, side effects, calculations and the system of record always belong to the deterministic core."],
  ["«constraint»&#xa;Narrator narrates facts only đã tính sẵn; không tự tạo hoặc làm tròn lại số liệu.", "«constraint»&#xa;The narrator only explains precomputed facts; it cannot invent or recompute numbers."],
  ["OCR và STT chỉ tạo raw text có thể kiểm tra; sau bước confirm, cả hai nhánh hội tụ vào pipeline giao dịch dùng chung.", "OCR and STT only produce reviewable raw text; after confirmation, both branches converge on the shared transaction pipeline."],
  ["Nhánh lỗi hoặc cancel, no data write", "Error/cancel branch with no data write"],
  ["Mẫu sửa được truy hồi làm context; hệ thống không fine-tune và chỉ re-tag sau khi người dùng confirm kế hoạch có TTL.", "Corrections are retrieved as context; the system does not fine-tune and only re-tags after the user confirms a TTL-bound plan."],
  ["Save transaction&#xa;đã confirm", "Save transaction&#xa;after confirmation"],
  ["Cancel / hết hạn", "Cancel / expired"],
  ["Nhánh cancel hoặc hết hạn, không ghi gì", "Cancel/expiry branch with no write"],
  ["Color Legend vùng trách nhiệm", "Responsibility-zone Legend"],
  ["Zone 2 · confirm và ghi feedback", "Zone 2 · confirm and store feedback"],
  ["Planning có công thức và cảnh báo", "Plan with formulas and warnings"],
  ["Kết quả", "Result"],
  ["Không tạo kế hoạch", "No plan created"],
  ["Kết quả chưa lưu", "Unsaved result"],
  ["hoặc quay lại sửa", "or return to edit"],
  ["No / sửa", "No / edit"],
  ["Cảnh báo và nhánh no data write", "Warning branch with no data write"],
  ["Sơ đồ ngữ cảnh và phạm vi hệ thống PERFIN", "PERFIN System Context and Scope"],
  ["Lõi xác định nằm trong biên hệ thống; LLM/OCR/STT là dịch vụ ngoài chỉ trả draft.", "The deterministic core is inside the system boundary; external LLM/OCR/STT services only return drafts."],
  ["nhập liệu • xác nhận • xem insight", "enter data • confirm • view insights"],
  ["Ứng dụng di động", "Mobile Application"],
  ["form • chat • media • preview", "forms • chat • media • preview"],
  ["Biên hệ thống PERFIN", "PERFIN System Boundary"],
  ["API + service nghiệp vụ", "API + business services"],
  ["Analytics • Budget • Goal Planner", "Analytics • Budget • Goal Planner"],
  ["Dịch vụ ngoài", "External Services"],
  ["chỉ trả draft / raw text", "return drafts / raw text only"],
  ["Ngoài phạm vi niên luận", "Outside the Project Scope"],
  ["Open Banking • shared wallet • auth production", "Open Banking • shared wallets • production auth"],
  ["thao tác / kết quả", "actions / results"],
  ["tool call / media", "tool call / media"],
  ["draft / raw text", "draft / raw text"],
  ["không bao gồm", "excluded"],
  ["Giao diện &amp; lõi xác định", "UI and deterministic core"],
  ["Dịch vụ ngoài (LLM/OCR/STT)", "External services (LLM/OCR/STT)"],
  ["Ngoài phạm vi", "Out of scope"],

  ["Kiến trúc vận hành PERFIN", "PERFIN Runtime Architecture"],
  ["Lõi xác định tạo và lưu facts; AI Orchestrator chỉ điều phối ngữ nghĩa.", "The deterministic core creates and stores facts; the AI Orchestrator only coordinates semantics."],
  ["UI + API client", "UI + API client"],
  ["route • upload • validation", "routing • upload • validation"],
  ["clarification • preview • confirm", "clarification • preview • confirmation"],
  ["transaction • recurring • export", "transactions • recurring • export"],
  ["schedule • retry • dedup", "scheduling • retry • deduplication"],
  ["typed draft • narration", "typed drafts • narration"],
  ["hàm xác định, kiểm thử độc lập", "deterministic, independently tested functions"],
  ["pending • cache • queue", "pending state • cache • queue"],
  ["provider có thể thay thế", "replaceable providers"],
  ["nguồn dữ liệu chuẩn", "system of record"],
  ["chat / media", "chat / media"],
  ["CRUD / query", "CRUD / queries"],
  ["trạng thái job", "job state"],
  ["draft có kiểu", "typed draft"],
  ["dữ liệu chuẩn", "authoritative data"],
  ["queue / fingerprint", "queue / fingerprint"],

  ["Sơ đồ triển khai nguyên mẫu PERFIN", "PERFIN Prototype Deployment Diagram"],
  ["Node ghi đầy đủ stereotype UML; mọi communication path đều ghi giao thức và cổng. Chỉ provider ngôn ngữ bên ngoài nằm ngoài biên triển khai; media inference chạy cục bộ.", "Nodes use UML stereotypes; every communication path names its protocol and port. Only the external language provider remains outside the deployment boundary; media inference is local."],
  ["«execution environment» Môi trường demo / thực nghiệm", "«execution environment» Demo / Experiment Environment"],
  ["Ngoài biên triển khai · external language provider", "Outside Deployment Boundary · External Language Provider"],
  ["Thiết bị người dùng", "User Device"],
  ["Ổ đĩa máy chủ demo", "Demo Server Disk"],
  ["Python cục bộ", "Local Python"],
  ["Python 3.11 cục bộ", "Local Python 3.11"],
  ["OCR · STT cục bộ", "Local OCR · STT"],
  ["Chú giải màu", "Color Legend"],
  ["Tiến trình ứng dụng trong biên", "In-boundary application process"],
  ["Lưu trữ bền vững, dữ liệu chuẩn", "Persistent authoritative storage"],
  ["Lưu trữ tạm, hàng đợi, tệp đĩa", "Temporary state, queue and disk files"],
  ["Thành phần AI (nét đứt: ngoài biên)", "AI component (dashed: external)"],
  ["Chú giải ký hiệu", "Notation Legend"],
  ["Communication path + giao thức", "Communication path + protocol"],
  ["Phụ thuộc ra dịch vụ ngoài biên", "Dependency on an external service"],
  ["«deploy»: artifact trên node", "«deploy»: artifact on a node"],

  ["Mô hình lớp miền theo aggregate nghiệp vụ", "UML Domain Class Model by Business Aggregate"],
  ["Quan hệ ghi đầy đủ ký hiệu UML: hình thoi đặc = composition, hình thoi rỗng = aggregation, mũi tên = navigability, bội số ghi ở cả hai đầu kèm role name. User là gốc sở hữu của cả bốn aggregate.", "Relationships use UML notation: filled diamond = composition, hollow diamond = aggregation, arrow = navigability, and multiplicities appear at both ends. User owns all four aggregates."],
  ["Hồ sơ &amp; cá nhân hóa", "Profile and Personalization"],
  ["Sổ cái", "Ledger"],
  ["Kế hoạch &amp; định kỳ", "Planning and Recurring"],
  ["Hội thoại &amp; phản hồi", "Conversation and Feedback"],
  ["Hồ sơ và hội thoại", "Profile and conversation"],
  ["Sổ cái xác định", "Deterministic ledger"],
  ["Kế hoạch và khoản định kỳ", "Planning and recurring data"],
  ["Thành phần liên quan LLM", "LLM-related component"],
  ["Composition: con phụ thuộc vòng đời cha", "Composition: child lifecycle depends on parent"],
  ["Aggregation: con tồn tại độc lập", "Aggregation: child exists independently"],
  ["Association có navigability (hướng đọc)", "Association with navigability"],
  ["Tham chiếu lỏng qua FK nullable", "Loose reference through a nullable FK"],

  ["Sơ đồ quan hệ thực thể vật lý", "Physical Entity–Relationship Diagram"],
  ["Tên cột được rút gọn theo nhóm để giữ khả năng đọc; kiểu dữ liệu và constraint đầy đủ là chuỗi migration 001–009. Mọi cạnh FK đều ghi lực lượng bằng ký hiệu chân chim ở hai đầu. Các FK phạm vi người dùng (user_id) được khai báo trong hộp bảng thay cho đường dài; cạnh chỉ vẽ cho quan hệ nghiệp vụ chính và quan hệ 1:1 duy nhất (users–backup_config).", "Columns are grouped for readability; migrations 001–009 define complete types and constraints. FK edges use crow's-foot cardinality. User-scope FKs are declared inside table boxes to avoid long crossing edges; only key business relations and the users–backup_config 1:1 relation are drawn."],
  ["Hồ sơ &amp; AI", "Profile and AI"],
  ["Kế hoạch", "Planning"],
  ["Định kỳ &amp; vận hành", "Recurring and Operations"],
  ["Ba bảng EXPORT_HISTORY, BACKUP_CONFIG và RECURRING_SUGGESTIONS_DISMISSED chỉ tham chiếu USERS qua user_id. Đường nối được thay bằng khai báo FK trong hộp bảng, lực lượng ghi ngay cạnh tên FK (N:1, riêng BACKUP_CONFIG là 1:1).", "EXPORT_HISTORY, BACKUP_CONFIG and RECURRING_SUGGESTIONS_DISMISSED only reference USERS through user_id. Their long edges are replaced by FK declarations inside each table box, including cardinality (N:1; BACKUP_CONFIG is 1:1)."],
  ["Chú giải lực lượng quan hệ", "Relationship Cardinality Legend"],
  ["Đúng một bản ghi (1)", "Exactly one record (1)"],
  ["Không hoặc một (0..1)", "Zero or one (0..1)"],
  ["Không hoặc nhiều (0..N)", "Zero or many (0..N)"],
  ["FK nullable / tham chiếu lỏng", "Nullable FK / loose reference"],
  ["Hồ sơ, hội thoại và vận hành", "Profile, conversation and operations"],
  ["Dữ liệu liên quan LLM", "LLM-related data"],

  ["Ranh giới trách nhiệm của LLM", "LLM Responsibility Boundary"],
  ["LLM chỉ chuyển đổi ngữ nghĩa và diễn giải facts; validation, side effect, phép tính và nguồn dữ liệu chuẩn luôn thuộc lõi xác định.", "The LLM only performs semantic conversion and fact narration; validation, side effects, calculations and the system of record always belong to the deterministic core."],
  ["Đầu vào tự nhiên", "Natural-language input"],
  ["Tiền xử lý xác định", "Deterministic preprocessing"],
  ["chuẩn hóa · giới hạn · nạp danh mục", "normalize · constrain · load categories"],
  ["Bộ định tuyến", "Semantic router"],
  ["ngữ nghĩa?", "route?"],
  ["schema ứng viên", "candidate schema"],
  ["Local parser / rules", "Local parser / rules"],
  ["baseline + fallback", "baseline + fallback"],
  ["Lệnh có kiểu", "Typed command"],
  ["Kiểm tra schema và luật miền", "Schema and domain validation"],
  ["Đủ và", "Complete and"],
  ["không mơ hồ?", "unambiguous?"],
  ["Hỏi làm rõ nhiều lượt", "Multi-turn clarification"],
  ["state có TTL", "state with TTL"],
  ["Bản xem trước", "Preview"],
  ["không có side effect", "no side effect"],
  ["xác nhận?", "confirm?"],
  ["Sửa / hủy", "Edit / cancel"],
  ["không ghi dữ liệu", "no data write"],
  ["Dịch vụ nghiệp vụ xác định", "Deterministic business service"],
  ["SQL transaction / rollback", "SQL transaction / rollback"],
  ["SQL + giải thuật phân tích", "SQL + analytics algorithms"],
  ["facts và dự báo", "facts and forecasts"],
  ["Insight facts có cấu trúc", "Structured insight facts"],
  ["nguồn sự thật định lượng", "quantitative source of truth"],
  ["chỉ diễn giải facts", "narrates facts only"],
  ["Lời giải thích có căn cứ", "Grounded explanation"],
  ["hoặc template fallback", "or template fallback"],
  ["LLM chỉ sinh lệnh có kiểu để lõi xác định kiểm tra; không truy cập DB và không thực thi side effect.", "The LLM only proposes typed commands for deterministic validation; it cannot access the database or execute side effects."],
  ["Narrator chỉ diễn giải facts đã tính sẵn; không tự tạo hoặc làm tròn lại số liệu.", "The narrator only explains precomputed facts; it cannot invent or recompute numbers."],
  ["ngữ cảnh phức tạp", "complex context"],
  ["câu đơn giản / fallback", "simple input / fallback"],
  ["người dùng bổ sung thông tin", "user provides missing data"],
  ["sửa draft", "edit draft"],
  ["Dữ liệu và trạng thái trung gian", "Intermediate data and state"],
  ["Lõi xác định: kiểm tra, tính toán, ghi dữ liệu", "Deterministic core: validate, compute and write"],
  ["Thành phần LLM (viền nét đứt)", "LLM component (dashed border)"],
  ["Điểm quyết định của luồng", "Decision point"],
  ["Nhánh từ chối, hỏi lại và ràng buộc an toàn", "Rejection, clarification and safety branch"],

  ["Máy trạng thái hội thoại và giao dịch chờ", "Conversation and Pending Transaction State Machine"],
  ["Clarification và pending dùng TTL; chỉ nhánh xác nhận mới được claim nguyên tử và tạo side effect.", "Clarification and pending states have TTLs; only confirmation can atomically claim a draft and create a side effect."],
  ["entry / xóa ngữ cảnh cũ", "entry / clear old context"],
  ["do / trích intent và slot", "do / extract intent and slots"],
  ["from text · OCR · STT", "from text · OCR · STT"],
  ["do / hỏi slot còn thiếu", "do / ask for missing slots"],
  ["keep candidates (Redis TTL)", "keep candidates (Redis TTL)"],
  ["entry / dựng bản xem trước", "entry / build preview"],
  ["entry / claim nguyên tử", "entry / atomic claim"],
  ["do / COMMIT giao dịch", "do / COMMIT transaction"],
  ["entry / bỏ pending, không ghi DB", "entry / discard pending, no DB write"],
  ["entry / xóa state trong Redis", "entry / delete Redis state"],
  ["tin nhắn người dùng", "user message"],
  ["mở phiên", "open session"],
  ["parsed [thiếu slot bắt buộc]", "parsed [required slot missing]"],
  ["hỏi slot kế tiếp", "ask for next slot"],
  ["parsed [đủ slot] / dựng preview", "parsed [complete] / build preview"],
  ["trả lời [vẫn còn slot thiếu]", "reply [slots still missing]"],
  ["cập nhật slot", "update slots"],
  ["trả lời [đủ slot]", "reply [complete]"],
  ["dựng preview", "build preview"],
  ["sửa slot", "edit slot"],
  ["mở lại thu thập", "resume collection"],
  ["xác nhận", "confirm"],
  ["claim rồi COMMIT", "claim then COMMIT"],
  ["hủy / xóa pending", "cancel / delete pending"],
  ["dọn ngữ cảnh", "clear context"],
  ["hủy", "cancel"],
  ["dừng thu thập", "stop collection"],
  ["COMMIT thất bại", "COMMIT failed"],
  ["Cú pháp chuyển tiếp: trigger [guard] / effect. after(TTL) là trigger thời gian do Redis đặt hạn. Đĩa đen là pseudostate khởi tạo, vòng bao là trạng thái kết thúc phiên; yêu cầu mới bắt đầu một phiên idle khác.", "Transition syntax: trigger [guard] / effect. after(TTL) is a Redis expiration trigger. The filled dot is the initial pseudostate and the ring ends the session; a new request starts another idle session."],
  ["Trạng thái chỉ đọc, chưa có dữ liệu chờ", "Read-only state with no pending data"],
  ["Có state tạm trong Redis kèm TTL", "Temporary Redis state with TTL"],
  ["Trạng thái duy nhất được ghi dữ liệu", "Only state allowed to write data"],
  ["Kết thúc không tạo hiệu ứng nào", "Terminal state with no side effect"],

  ["Luồng xử lý đầu vào đa phương thức", "Multimodal Input Processing Flow"],
  ["OCR và STT chỉ tạo raw text có thể kiểm tra; sau bước xác nhận, cả hai nhánh hội tụ vào pipeline giao dịch dùng chung.", "OCR and STT only produce reviewable raw text; after confirmation, both branches converge on the shared transaction pipeline."],
  ["Người dùng chọn ảnh hoặc ghi âm", "User selects an image or recording"],
  ["kiểm tra loại · giới hạn 10 MB", "validate type · 10 MB limit"],
  ["Loại đầu vào?", "Input type?"],
  ["Có văn bản thật?", "Valid raw text?"],
  ["không tạo dữ liệu giả", "do not fabricate data"],
  ["Raw text + thông tin provider", "Raw text + provider metadata"],
  ["Người dùng xác nhận /", "User confirms /"],
  ["sửa transcript", "edits transcript"],
  ["Hóa đơn", "Receipt"],
  ["nhiều dòng?", "multiple items?"],
  ["Chọn lưu tổng hoặc", "Choose receipt total or"],
  ["từng mặt hàng", "individual items"],
  ["text → transaction schema", "text → transaction schema"],
  ["Chuẩn hóa amount · type · date · category", "Normalize amount · type · date · category"],
  ["đánh dấu source + original_text", "record source + original_text"],
  ["Pending preview có TTL", "Pending preview with TTL"],
  ["Xác nhận?", "Confirm?"],
  ["lưu giao dịch · cập nhật ví", "save transaction · update wallet"],
  ["Kết quả có thể kiểm tra lại", "Auditable result"],
  ["Kết thúc lỗi", "Error outcome"],
  ["Đã hủy", "Cancelled"],
  ["Ảnh", "Image"],
  ["Âm thanh", "Audio"],
  ["Không", "No"],
  ["Voice", "Voice"],
  ["Đồng ý", "Confirm"],
  ["Sửa", "Edit"],
  ["Hủy", "Cancel"],
  ["thử lại", "retry"],
  ["Dữ liệu thô chưa kiểm chứng (ảnh, âm thanh, raw text)", "Unverified raw data (image, audio, raw text)"],
  ["Thành phần AI ngoài: OCR, STT, LLM parser", "External AI: OCR, STT and LLM parser"],
  ["Điểm quyết định và dữ liệu tạm có TTL", "Decision and TTL-bound state"],
  ["Bước cần người dùng xem lại", "User review step"],
  ["Lõi xác định: chuẩn hóa, ghi dữ liệu, kết quả", "Deterministic core: normalize, write and return results"],
  ["Nhánh lỗi hoặc hủy, không ghi dữ liệu", "Error/cancel branch with no data write"],

  ["Luồng phản hồi và cá nhân hóa phân loại", "Classification Feedback and Personalization Flow"],
  ["Mẫu sửa được truy hồi làm context; hệ thống không fine-tune và chỉ re-tag sau khi người dùng xác nhận kế hoạch có TTL.", "Corrections are retrieved as context; the system does not fine-tune and only re-tags after the user confirms a TTL-bound plan."],
  ["1 · Correction retrieval", "1 · Correction Retrieval"],
  ["2 · Xác nhận và ghi feedback", "2 · Confirm and Store Feedback"],
  ["3 · Đề xuất danh mục và re-tag có kiểm soát", "3 · Propose Categories and Controlled Re-tagging"],
  ["Giao dịch mới", "New transaction"],
  ["text · OCR · voice", "text · OCR · voice"],
  ["Nạp tối đa 200", "Load up to 200"],
  ["feedback gần đây", "recent corrections"],
  ["Chuẩn hóa tiếng Việt", "Normalize Vietnamese text"],
  ["Xếp hạng ví dụ tương tự", "Rank similar examples"],
  ["ngưỡng 0,35 · tối đa 5", "threshold 0.35 · max 5"],
  ["LLM function calling", "LLM function calling"],
  ["hoặc local parser", "or local parser"],
  ["Correction", "Correction"],
  ["đủ mạnh?", "strong enough?"],
  ["Ghi đè category ứng viên", "Override candidate category"],
  ["confidence + match kind", "confidence + match kind"],
  ["cho người dùng", "for user review"],
  ["sửa kết quả AI?", "correct AI result?"],
  ["Lưu ai_feedback_logs", "Store ai_feedback_logs"],
  ["classification / extraction", "classification / extraction"],
  ["Lưu giao dịch", "Save transaction"],
  ["đã xác nhận", "after confirmation"],
  ["Lọc giao dịch thuộc", "Filter transactions in"],
  ["danh mục Khác", "the Other category"],
  ["Gom cụm mô tả", "Cluster descriptions"],
  ["similarity &gt;= 0,90 · tối thiểu 3", "similarity &gt;= 0.90 · minimum 3"],
  ["Đề xuất danh mục mới", "Propose a new category"],
  ["kèm evidence + confidence", "with evidence + confidence"],
  ["Xác nhận kế hoạch", "Confirm re-tag plan"],
  ["re-tag có TTL?", "with TTL?"],
  ["BEGIN · tạo / tái dùng category", "BEGIN · create / reuse category"],
  ["re-tag &lt;= 200 · ghi feedback · COMMIT", "re-tag &lt;= 200 · store feedback · COMMIT"],
  ["Mẫu sửa dùng cho", "Correction is available for"],
  ["lần nhập sau", "future inputs"],
  ["Kết thúc hoặc chờ thêm dữ liệu", "Finish or wait for more data"],
  ["Bước có gọi LLM", "Step that calls the LLM"],
  ["Tính toán xác định trên dữ liệu đã có", "Deterministic computation on stored data"],
  ["Trạng thái dữ liệu và tương tác người dùng", "Data state and user interaction"],
  ["Ghi dữ liệu trong một transaction", "Data write in one transaction"],
  ["Nhánh hủy hoặc hết hạn, không ghi gì", "Cancel/expiry branch with no write"],
  ["Chú giải màu vùng trách nhiệm", "Responsibility-zone Legend"],
  ["Zone 1 · truy hồi mẫu sửa", "Zone 1 · retrieve corrections"],
  ["Zone 2 · xác nhận và ghi feedback", "Zone 2 · confirm and store feedback"],
  ["Zone 3 · đề xuất danh mục và re-tag", "Zone 3 · propose categories and re-tag"],

  ["Luồng lập kế hoạch mục tiêu và mô phỏng what-if", "Goal Planning and What-if Flow"],
  ["Mức góp, thời gian và cảnh báo được tính bằng công thức xác định; chỉ thao tác lưu cuối cùng mới ghi financial_goals.", "Contributions, duration and warnings are computed deterministically; only the final save action writes financial_goals."],
  ["Mục tiêu", "Goal"],
  ["saving · purchase · debt payoff", "saving · purchase · debt payoff"],
  ["Kiểm tra amount · date · rate · contribution", "Validate amount · date · rate · contribution"],
  ["Dữ liệu", "Input"],
  ["hợp lệ?", "valid?"],
  ["Trả lỗi theo field", "Return field-level errors"],
  ["hoặc hỏi làm rõ", "or request clarification"],
  ["Tính dòng tiền có thể phân bổ", "Compute allocatable cash flow"],
  ["từ lịch sử thu – chi", "from income and expense history"],
  ["Loại mục tiêu?", "Goal type?"],
  ["remaining = target − current", "remaining = target − current"],
  ["months = ceil(remaining / contribution)", "months = ceil(remaining / contribution)"],
  ["amortization theo từng tháng", "monthly amortization"],
  ["Payment có bù", "Does payment cover"],
  ["lãi tháng đầu?", "first-month interest?"],
  ["Cảnh báo negative amortization", "Warn about negative amortization"],
  ["hoặc horizon &gt; 600 tháng", "or horizon &gt; 600 months"],
  ["Tính requiredMonthly · projectedDate", "Compute requiredMonthly · projectedDate"],
  ["onTrack · gap · shortfall", "onTrack · gap · shortfall"],
  ["Kịch bản what-if", "What-if scenario"],
  ["thêm khoản góp mỗi tháng", "add a monthly contribution"],
  ["So actualPercent với expectedPercent", "Compare actualPercent with expectedPercent"],
  ["đánh dấu behind schedule", "flag behind schedule"],
  ["Kế hoạch có công thức và cảnh báo", "Plan with formulas and warnings"],
  ["lưu mục tiêu?", "save goal?"],
  ["tiếp tục với cảnh báo", "continue with warning"],
  ["Không / sửa", "No / edit"],
  ["Đầu vào của người dùng", "User input"],
  ["Công thức xác định: phân bổ, amortization, dự báo", "Deterministic formulas: allocation, amortization and forecasting"],
  ["Kết quả kế hoạch chưa ghi dữ liệu", "Unsaved plan result"],
  ["Cảnh báo và nhánh không ghi dữ liệu", "Warning branch with no data write"],

  ["Người dùng", "User"],
  ["Có", "Yes"],
  ["Chú giải", "Legend"],
];

for (const base of files) {
  const file = path.join(drawioDir, `${base}.drawio`);
  let xml = fs.readFileSync(file, "utf8");
  // Two passes resolve phrases that become partially translated after a
  // shorter shared replacement later in the table.
  for (let pass = 0; pass < 2; pass += 1) {
    for (const [source, target] of replacements) {
      xml = xml.split(source).join(target);
    }
  }
  // Keep the postprocessor idempotent when an already translated source is
  // processed again ("confirm" is a prefix of "confirmation").
  xml = xml.replace(/confirmation(?:ation)+/g, "confirmation");
  xml = xml
    .split("Result có thể kiểm tra lại").join("Auditable result")
    .split("Result kế hoạch chưa ghi dữ liệu").join("Unsaved plan result");
  fs.writeFileSync(file, xml, "utf8");
}

const vietnamese = /value="[^"]*[À-ỹĐđ][^"]*"/g;
let failed = false;
for (const base of files) {
  const file = path.join(drawioDir, `${base}.drawio`);
  const xml = fs.readFileSync(file, "utf8");
  const matches = xml.match(vietnamese) || [];
  if (matches.length) {
    failed = true;
    process.stderr.write(`${base}: untranslated labels\n${matches.join("\n")}\n`);
  }
}

if (failed) process.exit(1);
console.log(`Translated ${files.length} retained diagrams to English.`);
